"""add embedding columns

Revision ID: 7dfd16e2f029
Revises: 48a51027c837
Create Date: 2026-03-01 15:04:32.146739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7dfd16e2f029'
down_revision: Union[str, Sequence[str], None] = '48a51027c837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension (required before adding vector columns)
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('embedding', Vector(768), nullable=True))
    op.add_column('users', sa.Column('preference_vector', Vector(768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preference_vector')
    op.drop_column('brands', 'embedding')
    # ### end Alembic commands ###
