"""add auth fields to users

Revision ID: b5603f47b307
Revises: 7dfd16e2f029
Create Date: 2026-03-01 16:42:23.824865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5603f47b307'
down_revision: Union[str, Sequence[str], None] = '7dfd16e2f029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('has_completed_quiz', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_completed_quiz')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
